config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:new, :create] do
      member do
        post 'vote'
      end
    end
  end

  resources :users, only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  has_many :votes, as: :voteable

  validates :content, presence: true

  def total_votes
    self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  has_many :post_categories
  has_many :categories, through: :post_categories

  has_many :comments

  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true

  def total_votes
    self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password

  validates :name, presence: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def require_user
  	unless logged_in?
  		flash[:error] = "You must be logged in to perform this operation"
  		redirect_to root_path
  	end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_user

  def new
  end

  def create
    @comment = Comment.new
    @comment.content = params[:content]
    @comment.post_id = params[:post_id]
    @comment.user_id = session[:user_id]
    if @comment.save
      flash[:notice] = "New comment successfully created!"
      redirect_to post_path(params[:post_id])
    else
      flash[:alert] = "Comment can't be blank!"
      redirect_to new_post_comment_path(params[:post_id])
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    Vote.create(voteable: @comment, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id]) }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, only: [:new, :create, :edit, :update, :vote]

  def index
    @posts = Post.all
    @posts.sort! { |x,y| y.total_votes <=> x.total_votes }
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = session[:user_id]

    if @post.save
      flash[:notice] = "New post successfully created!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])

    if @post.user_id != session[:user_id]
      flash[:error] = "Posts can be edited only by owner"
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.user_id != session[:user_id]
      flash[:error] = "Posts can be edited only by owner"
      redirect_to posts_path
    end
    
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was successfully updated!"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    if @post.nil?
      flash[:alert] = "This post does NOT exist!"
      redirect_to posts_path
    else
      @comments = @post.comments
      @comments.sort! { |x,y| y.total_votes <=> x.total_votes }
    end
  end

  def vote
    @post = Post.find(params[:id])
    Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(name: params[:name]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you are logged in!"
      redirect_to root_path
    else
      flash[:error] = "Something wrong with the username or password!"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Thanks for registering!"
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<h5>Comments for post <%= @post.title %></h5>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Net votes</th>
    <% if logged_in? %>
      <th>Like</th>
      <th>Un-like</th>
    <% end %>
  </tr>

  <% @comments.each do |comment| %>
  	<tr>
	    <td><%= comment.content %></td>
	    <td><%= comment.user.name %></td>
	    <td><%= comment.total_votes %></td>
	    <% if logged_in? %>
	      <td><%= link_to "Like", vote_post_comment_path(@post.id, comment.id, vote: true), method: 'post' %></td>
	      <td><%= link_to "Un-like", vote_post_comment_path(@post.id, comment.id, vote: false), method: 'post' %></td>
	    <% end %>
    </tr>
  <% end %>
</table>
<br>

<% if logged_in? %>
	<%= link_to "Create new comment", new_post_comment_path(@post.id) %>
<% end %>
<br>
<%= link_to "Back to post summary page", post_path(@post.id) %>

app/views/comments/new.html.erb
<h5>Create a new comment</h5>
<% if logged_in? %>
  <%= form_tag post_comments_path do %>
    <%= label_tag :content %>
    <%= text_area_tag :content %>
    <br>
    <%= submit_tag "Create it!" %>
  <% end %>
  <br>
<% end %>

<div class="btn">
	<%= link_to "Back to post summary page", post_path(params[:post_id]) %>
</div>

app/views/comments/vote.js.erb
$("#comment_<%=@comment.id%>_votes").html(<%=@comment.total_votes%>);

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <% if logged_in? %>
	  <li>
	    <%= link_to 'Create a new post', new_post_path %>
	  </li>
	  <li>
	    <%= link_to "Logout (" + current_user.name + ")", logout_path %>
	  </li>
	<% else %>
	  <li>
	    <%= link_to 'Register', new_user_path %>
	  </li>
	  <li>
	    <%= link_to 'Login', login_path %>
	  </li>
	 <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Robert K - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<% if logged_in? %>

  <% if @post.errors.any? %>
    <div class='alert alert-error'>
      <%= @post.errors.full_messages.join("; ") %>
    </div>
  <% end %>

  <%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </br>
    <%= f.label :url %>
    <%= f.text_field :url %>
    </br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    </br>
    <%= f.submit %>
  <% end %>
  </br>

<% end %>

<div class="btn">
  <%= link_to "Back to main posts page", posts_path %>
</div>

app/views/posts/edit.html.erb
<h5>Editing post <%= @post.title %> </h5>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="well well-large">
  <h3>Welcome to RK PostIt application!</h3>
</div>

<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Summary</th>
    <th>User</th>
    <th>Net votes</th>
    <% if logged_in? %>
      <th>Edit</th>
      <th>Like</th>
      <th>Un-like</th>
    <% end %>
  </tr>

  <% @posts.each do |post| %>
  <tr>
    <td><%= link_to post.title, post_path(post.id) %></td>
    <td><%= post.url %></td>
    <td><%= post.user.name %></td>
    <td><span id="post_<%=post.id%>_votes"><%= post.total_votes %></span></td>
    <% if logged_in? %>
      <td><%= link_to "→", edit_post_path(post.id) %></td>
      <td><%= link_to '<i class="icon-chevron-up"></i>'.html_safe, vote_post_path(post.id, vote: true), method: 'post', remote: true %></td>
      <td><%= link_to '<i class="icon-chevron-down"></i>'.html_safe, vote_post_path(post.id, vote: false), method: 'post', remote: true %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<br>

<% if logged_in? %>
  <div class="btn">
    <%= link_to "Create new post", new_post_path %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h5>Create a new post</h5>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="well well-large">
  <h3>Showing <%= @post.title %></h3>

  <strong>Title:</strong>
  <%= @post.title %>
  <br>
  <strong>Url:</strong>
  <%= @post.url %>
  <br>
  <strong>Description:</strong>
  <%= @post.url %>
  <br>
  <strong>User name:</strong>
  <%= @post.user.name %>
  <br><br>

  <% if logged_in? %>
    <div class="btn">
      <%= link_to "Edit post", edit_post_path(@post.id) %>
      <br>
    </div>
  <% end %>

  <div class="btn">
    <%= link_to "Back to main posts page", posts_path %>
  </div>
</div>

<h5>
  Comments for this post 
  <% if logged_in? %>
    (<%= link_to "Create new comment", new_post_comment_path(@post.id) %>)
  <% end %>
</h5>

<table class="table table-hover">
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Net votes</th>
    <% if logged_in? %>
      <th>Like</th>
      <th>Un-like</th>
    <% end %>
  </tr>

  <% @comments.each do |comment| %>
  	<tr>
	    <td><%= comment.content %></td>
	    <td><%= comment.user.name %></td>
	    <td><span id="comment_<%=comment.id%>_votes"><%= comment.total_votes %></span></td>
	    <% if logged_in? %>
	      <td><%= link_to '<i class="icon-chevron-up"></i>'.html_safe, vote_post_comment_path(@post.id, comment.id, vote: true), method: 'post', remote: true %></td>
	      <td><%= link_to '<i class="icon-chevron-down"></i>'.html_safe, vote_post_comment_path(@post.id, comment.id, vote: false), method: 'post', remote: true %></td>
	    <% end %>
    </tr>
  <% end %>
</table>

app/views/posts/vote.js.erb
$("#post_<%=@post.id%>_votes").html(<%=@post.total_votes%>);

app/views/users/new.html.erb
<h5>Register a new user</h5>

<% if @user.errors.any? %>
  <div class='alert alert-error'>
    <%= @user.errors.full_messages.join("; ") %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Register" %>
<% end %>